# events { }

# http {
#   server {
#     listen 80;

#     location / {
#       proxy_pass http://frontend:5173;
#     }

#     location /api/ {
#       proxy_pass http://backend:8000/;
#     }
#   }
# }events { }

http {
  limit_req_zone $binary_remote_addr zone=api_per_ip:10m rate=20r/s;

  limit_req_zone $binary_remote_addr zone=login_per_ip:10m rate=5r/m;

  limit_req_status 429;

  server {
    listen 80;

    location / {
      proxy_pass http://frontend:5173;
    }

    location = /api/auth/login {
      limit_req zone=login_per_ip burst=5 nodelay;

      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

      proxy_pass http://backend:8000/auth/login;
    }

    location /api/ {
      limit_req zone=api_per_ip burst=40 nodelay;

      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

      proxy_pass http://backend:8000/;
    }
  }
}events { }
