[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "lab_system_backend"
version = "0.1.0"
requires-python = ">=3.11"

[tool.setuptools]
packages = ["src", "src.api"]
package-dir = {"" = "."}
